### ISSUE TITLE
Implement Embedded and Event SubProcess element

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/processmaker#3410] opened 2020-10-06 13:51 UTC
**Implement Embedded and Event Subprocess element**
Embedded subprocess element:
![image](https://user-images.githubusercontent.com/8028650/95209942-ee667100-07b8-11eb-9fb2-b89a7bf5a4b6.png)

A subprocess is an activity that contains other activities, gateways, events, etc., which itself forms a process that is part of a bigger process. A subprocess is completely defined inside a parent process (that’s why it’s often called an embedded Subprocess).

Subprocesses have two major use cases:

- Subprocesses allow hierarchical modeling. Many modeling tools allow that subprocesses can be collapsed, hiding all the details of the subprocess and displaying a high-level, end-to-end overview of the business process.
- A subprocess creates a new scope for events. Events that are thrown during execution of the subprocess can be caught by a boundary event on the boundary of the subprocess, thus creating a scope for that event, limited to the subprocess.

Event subprocess:
![image](https://user-images.githubusercontent.com/8028650/95210125-279ee100-07b9-11eb-88e4-f8ea1eda64ed.png)

The event subprocess is a subprocess that is triggered by an event. An event subprocess can be added at the process level or at any subprocess level. The event used to trigger an event subprocess is configured using a start event. Therefore, none start events are not supported for event subprocesses. An event subprocess might be triggered using events like message events, error events, signal events, timer events, or compensation events. The subscription to the start event is created when the scope (process instance or subprocess) hosting the event subprocess is created. The subscription is removed when the scope is ended.

**Comment by velkymx** [comment] 2020-12-10 15:18
Duplicate of #3411

**Closed by velkymx** 2020-12-10 15:18 UTC
