### ISSUE TITLE
Assigned User File Download Issue

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2084] opened 2019-07-08 19:40 UTC
When a user opens a task assigned to them, if the form has a File Download control but the user is not an admin, the Screen will show an Authorization error, and the file will be inaccessible. If the user has admin privileges, he'd see no error and be able to download the file just fine. This is unacceptable, since if the user has a task assigned, they should naturally be able to fetch download files part of the form. 

Replicate:
- Create a screen with a File Upload control
- Create a screen with a File Download control, same variable
- Add screens to two serial tasks, each assigned to different (non admin) users.
- Run the request, add a file as user one. Submit.
- Upon opening the assigned task, user two will encounter this (notice the error above, and the file control):

**Comment by nolanpro** [comment] 2019-07-15 21:31
@velkymx @caleeli the PR would allow any participant to upload files at any time during the request. Is the the intended behavior or should it only be the person assigned to the task, like a regular task update?

**Comment by caleeli** [comment] 2019-07-18 15:04
Actually we have an endpoint limitation, we know the user and the request where we are uploading the file, but not the task or screen, that's why the validation was made by participant instead of person assigned to the task

**Comment by caleeli** [comment] 2019-07-18 15:27
@velkymx @nolanpro, I've reviewed the PM3 API, and I found that the upload endpoint has the following logic:

CAN UPLOAD IF: User is assigned to the task, or is a Supervisor assigned to the process with enabled permission to upload files into the process requests.

the API structure is the following:

```
POST /api/1.0/{workspace}/cases/{app_uid}/input-document
Body:
{
    "inp_doc_uid": "",
    "tas_uid": "",
    "app_doc_comment": "",
    "form": ""
}
```
It includes the app_uid (Request ID), task_uid (Task ID), and inp_doc_uid (Screen ID)

**Comment by nolanpro** [comment] 2019-07-18 16:23
@caleeli yeah it seems like we could modify our payload to include the task id. The controller can check if the task is active and if the user has permission to modify the task. Is that something you can do as part of this PR?

**Closed** 2019-07-18 16:57 UTC
Labels: P2, Pull Request, bug, question, review
