### ISSUE TITLE
Signals in Modeler

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2990] opened 2020-03-25 15:35 UTC
We need to setup the modeler so that the Signal throw registers to the Signal queue and the Signals catch can read the queue and offer a list of signals to catch. Similar to the message throw / catch.

**Comment by PMQABen** [comment] 2020-04-03 21:01
Error when trying to save a process with a signal event that does not use the `node_0000` formatting:
```
Undefined index: signalRef
vendor.js?id=a1b418d96899f59174b4:15777
PUT http://bpm4.local.processmaker.com/api/1.0/processes/2 500 (Internal Server Error)
```
Related schema validation error that doesn't go away:
```
Schema Validation
Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}signal', attribute 'id': '1' is not a valid value of the atomic type 'xs:ID'.
```

When trying to unselect a previously selected Signal ID trigger:
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'id' of null"
found in
---> <VueMultiselect>
       <SignalSelect> at resources/js/processes/modeler/components/inspector/SignalSelect.vue
         <BCollapse>
           <FormAccordion>
             <VueFormRenderer>
               <InspectorPanel>
                 <Modeler>
                   <ModelerApp> at resources/js/processes/modeler/components/ModelerApp.vue
                     <Root>
```
The user can wipe out additional created signal triggers by switching to a different signal trigger. Zipped video: [signal.mp4.zip](https://github.com/ProcessMaker/processmaker/files/4429888/signal.mp4.zip)

Video, problems creating additional signal triggers: [Signal Test 1.mp4.zip](https://github.com/ProcessMaker/processmaker/files/4429893/Signal.Test.1.mp4.zip)

**Comment by ZLTM** [comment] 2020-04-06 17:21
Process with a signal and without a task wont complete

Steps to Reproduce:

- Create a flow with a task throw and catch
- 
- Run the process
- 
- Add a task between the throw and catch
- 
- Run the process

Current Behavior:
The process only completes if there is a task
https://www.dropbox.com/s/y6132jtb2x6fry6/2020-04-06%2010-06-30.mp4?dl=0

Expected Behavior:
The process should complete even if there is no task between throw and catch

**Comment by PMQABen** [comment] 2020-04-06 17:21
**More issues:**
A signal process without a task wont complete: [(video) 2020-04-06 10-06-30.mp4.txt](https://github.com/ProcessMaker/processmaker/files/4439772/2020-04-06.10-06-30.mp4.txt)

---
1. Create a new signal and populate the values
2. Create another signal and select it
**Result:** The new signal keeps the populated values from a previously created signal: [(video) 2020-04-06 09-09-28.mp4.txt](https://github.com/ProcessMaker/processmaker/files/4439800/2020-04-06.09-09-28.mp4.txt)

---
Missing translation strings in the en.json file for "Not found" and "Signal that will trigger this start event"
![image](https://user-images.githubusercontent.com/28575916/78585565-ee2bef80-77ee-11ea-9a6a-3b0ad54d8731.png)

---
1. Create two different signal events
2. Open the create signal interface on the first signal event
3. Click on the second signal event
4. Open the edit signal interface
5. Click back on the first signal event
**Result:** The edit interface remains even after selecting a different signal event: [(video) 2020-04-06 08-57-45.mp4.txt](https://github.com/ProcessMaker/processmaker/files/4439841/2020-04-06.08-57-45.mp4.txt)

---
1. Create a signal event
2. Open the create new signal interface
3. Open the edit signal interface
**Result:** The interface remains there even after another signal is clicked.

**Comment by ZLTM** [comment] 2020-04-06 17:24
Previous data remains on a new signal creation

Steps to Reproduce:

- Create a new signal

- Create another one

Current Behavior:
The second signal conserves the values of the first one
https://www.dropbox.com/s/2139h4awq6l9soz/2020-04-06%2009-09-28.mp4?dl=0

Expected Behavior:
Show blank fields when creating a new signal

**Comment by PMQABen** [comment] 2020-04-08 22:54
* The same text string "Signal that will trigger this start event" is used for start, end, and intermediate signal events.

**Comment by PMQABen** [comment] 2020-04-21 20:31
Error 500 after making a request involving catch and throw signal elements

1. Create a flow connecting a throw and catch signal
2. Make a request for the flow

![image](https://user-images.githubusercontent.com/28575916/79910865-4b6d9680-83d4-11ea-8735-4512a88b1eb5.png)

Expected Behavior:
If the user would not be able to connect a throw signal to a catch signal we should not allow it

**Comment by caleeli** [comment] 2020-04-28 01:03
@PMQABen I reviewed and tested the process, the behavior is the expected, the process is not completed (with or without the Form Task) because from when the Intermediate Catch Signal Event is activated, it did not received or catch any signal to let the token continue to the end.

![signal_throw_catch](https://user-images.githubusercontent.com/8028650/80422212-c854b080-88ab-11ea-8d4b-c374898f0613.gif)

But the next time this process is started it should send the signal to complete the previous request.
The error produced when the ThrowEvent is connected directly to CatchEvent is fixed in this PR:

https://github.com/ProcessMaker/processmaker/pull/3075


![signal_throw_catch2](https://user-images.githubusercontent.com/8028650/80435143-bc77e700-88c9-11ea-99e9-9cf7de0d76b1.gif)

**Closed** 2020-04-28 16:32 UTC
Labels: P1
